# Generated by Django 4.2.11 on 2025-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Sender's name", max_length=200)),
                ("email", models.EmailField(help_text="Sender's email", max_length=254)),
                (
                    "phone",
                    models.CharField(blank=True, help_text="Sender's phone number", max_length=20),
                ),
                ("subject", models.CharField(help_text="Message subject", max_length=200)),
                ("message", models.TextField(help_text="Message content")),
                (
                    "is_read",
                    models.BooleanField(default=False, help_text="Whether message has been read"),
                ),
                (
                    "replied",
                    models.BooleanField(default=False, help_text="Whether we have replied"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
