# Generated by Django 4.2.11 on 2025-10-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Not used - email is used for authentication",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
    ]
