# Generated by Django 4.2.11 on 2025-10-23 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of week",
                        unique=True,
                    ),
                ),
                ("start_time", models.TimeField(help_text="Opening time")),
                ("end_time", models.TimeField(help_text="Closing time")),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Check if salon is closed this day"
                    ),
                ),
            ],
            options={
                "verbose_name": "Opening Hour",
                "verbose_name_plural": "Opening Hours",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g., 'Classic Haircut')", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of name", max_length=200, unique=True
                    ),
                ),
                ("description", models.TextField(help_text="Detailed service description")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, help_text="Brief description for listings", max_length=300
                    ),
                ),
                ("duration", models.IntegerField(help_text="Service duration in minutes")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, help_text="Service price", max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, help_text="Service image", null=True, upload_to="services/"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether service is available for booking"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which services are displayed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Staff member biography")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, help_text="Profile photo", null=True, upload_to="staff/"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, help_text="Staff member email", max_length=254),
                ),
                (
                    "phone",
                    models.CharField(blank=True, help_text="Staff member phone", max_length=20),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether staff member is available for booking"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Display order on staff page"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.ManyToManyField(
                        help_text="Services this staff member can provide",
                        related_name="staff_members",
                        to="booking.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["display_order", "first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Start date and time")),
                ("end_time", models.DateTimeField(help_text="End date and time")),
                (
                    "capacity",
                    models.IntegerField(
                        default=1, help_text="Number of bookings this slot can accommodate"
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False, help_text="Whether this slot is blocked (not available)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Staff member for this slot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="booking.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Slot",
                "verbose_name_plural": "Time Slots",
                "ordering": ["start_time"],
                "unique_together": {("staff", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Appointment start time")),
                ("end_time", models.DateTimeField(help_text="Appointment end time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        help_text="Booking status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes or special requests"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price at time of booking", max_digits=10
                    ),
                ),
                (
                    "confirmation_code",
                    models.CharField(
                        help_text="Unique confirmation code", max_length=32, unique=True
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="When booking was confirmed", null=True
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, help_text="Whether reminder notification was sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who made the booking",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being booked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="booking.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Staff member providing service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="booking.staff",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        help_text="Time slot for appointment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="booking.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
