# Generated by Django 4.2.11 on 2025-10-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(
                blank=True, help_text="Guest email address (if not logged in)", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(
                blank=True, help_text="Guest full name (if not logged in)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(
                blank=True, help_text="Guest phone number (optional)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer who made the booking",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
